// <auto-generated />
using GladMMO;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GladMMO.Database.Global.Migrations
{
    [DbContext(typeof(GlobalDatabaseContext))]
    [Migration("20200706014414_AddedServiceEndpointMissingEndpoint")]
    partial class AddedServiceEndpointMissingEndpoint
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GladMMO.ServiceEndpointModel", b =>
                {
                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<int>("Locale")
                        .HasColumnType("int");

                    b.Property<int>("Mode")
                        .HasColumnType("int");

                    b.HasKey("ServiceId", "Locale", "Mode");

                    b.ToTable("service_endpoints");
                });

            modelBuilder.Entity("GladMMO.ServiceEntryModel", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("int");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.HasKey("ServiceId");

                    b.HasAlternateKey("ServiceName");

                    b.ToTable("services");
                });

            modelBuilder.Entity("GladMMO.ServiceEndpointModel", b =>
                {
                    b.HasOne("GladMMO.ServiceEntryModel", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("GladMMO.ResolvedEndpoint", "Endpoint", b1 =>
                        {
                            b1.Property<int>("ServiceEndpointModelServiceId")
                                .HasColumnType("int");

                            b1.Property<int>("ServiceEndpointModelLocale")
                                .HasColumnType("int");

                            b1.Property<int>("ServiceEndpointModelMode")
                                .HasColumnType("int");

                            b1.Property<string>("Address")
                                .HasColumnType("longtext CHARACTER SET utf8mb4");

                            b1.Property<int>("Port")
                                .HasColumnType("int");

                            b1.HasKey("ServiceEndpointModelServiceId", "ServiceEndpointModelLocale", "ServiceEndpointModelMode");

                            b1.ToTable("service_endpoints");

                            b1.WithOwner()
                                .HasForeignKey("ServiceEndpointModelServiceId", "ServiceEndpointModelLocale", "ServiceEndpointModelMode");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
